<h1><?php echo $this->titulo ?></h1>
<?php

    $form = $this->form;
    $form->prepare();
    
    // Assuming the "/video7/formulario/receive" route exists...
    $form->setAttribute('action', $this->url.'/video7/formulario/registro');

    // Set the method attribute for the form
    $form->setAttribute('method', 'post');

    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');

    // Render the opening tag
    echo $this->form()->openTag($form);
?>
<div class="form_element">
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
?>
</div>
<div class="form_element">
<?php
    $email = $form->get('email');
    echo $formLabel->openTag() . $email->getOption('label');
    echo $this->formInput($email);
    echo $this->formElementErrors($email);
    echo $formLabel->closeTag();
?>
</div>
<a class="btn btn-success">
    <?php
    //echo $this->formElement($form->get('security'));
    echo $this->formElement($form->get('send'));
    ?>
</a>
<?php
    echo $this->form()->closeTag($form);
?>