<div class="hero-unit">
    <h1><?php echo $this->titulo ?></h1>
</div>

<div class="row">

    <div class="span4">
        
    </div>

    <div class="span4">
        <h2><?php echo $this->subtitulo ?></h2>
        <a class="btn btn-success" href="<?php echo $this->basePath()?>/technodt/login/login" target="_parent"> <?php echo $this->login ?> &raquo;</a>
   </div>

   <div class="span4">
       
   </div>
</div>



