<h1><?php echo $this->titulo ?></h1>
<table style="width:400px;text-align: left;">
    <tr>
        <td colspan="3"><a class="btn btn-success" href="<?php echo $this->basePath()?>/video7/formulario/registro">Agregar Usuario</a></td>
    </tr>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Email</th>
    </tr>
    <?php foreach ($this->datos as $dato) { ?>
    <tr style="<?php echo $this->cycle(array('#cccccc','#f2f2f2'))->next() ?>">
        <td><?php echo $dato['id_usuario'] ?></td>
        <td><?php echo $dato['nombre'] ?></td>
        <td><?php echo $dato['email'] ?></td>
        <td>
            <a class="btn btn-success" href="<?php echo $this->basePath()?>/video7/index/ver/<?php echo $dato['id_usuario']?>">Ver</a>
        </td>
        <td>
            <a class="btn btn-success" href="<?php echo $this->basePath()?>/video7/index/ver/<?php echo $dato['id_usuario']?>">Editar</a>
        </td>
    </tr>
    
    <?php } 
    
    $this->cycle()->assign(array('#cccccc','#f2f2f2'));
    $this->cycle()->prev();
    ?>
    
    
</table>
