<div class="hero-unit">
    <p class="pagination-right">Est&aacute logueado como: <?php echo $this->email ?></p>
</div>
<div class="row">
    
    <div class="span4">
        
    </div>
    <div class="span4">
        <div></div>
        <div>
            <a class="btn btn-success" href="<?php echo $this->basePath()?>/technodt/login/login" target="_parent"> Crear Equipo &raquo;</a>
        </div>
        <br>
        <div>
            <a class="btn btn-success" href="<?php echo $this->basePath()?>/technodt/login/login" target="_parent"> Listar Tabla General del Torneo &raquo;</a>
        </div>
    </div>
    <div class="span4">
       
    </div>
</div>