<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Video7\Module'                        => __DIR__ . '/Module.php',
    'Video7\Controller\IndexController' => __DIR__ . '/src/Video7/Controller/IndexController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/Video7/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/Video7/SampleTest.php',
);